[package]
name = "macros"
version = "0.1.0"
authors = ["makslevental <maksim.levental@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
proc-macro2 = "1.0.26"
syn = { version = "1.0.71", features = ["extra-traits"] }
